#!/bin/bash
#
# Copyright (c) Authors: http://rearm.it
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# Functions:
#
# set_hdmi_audio

set_hdmi_audio() {
	local hw=$(aplay -l | grep hdmi | awk -F \: '/,/{print $1}' | awk '{print $2}')

	# create asound.conf
	cat > /etc/asound.conf << _EOF_
pcm.!default {
  type plug
  slave.pcm "dmixer"
}

pcm.dmixer  {
  type dmix
  ipc_key 1024
  slave {
    pcm "hw:$hw,0"
    period_time 0
    period_size 1024
    buffer_size 4096
    rate 44100
  }
  bindings {
    0 0
    1 1
  }
}

ctl.dmixer {
  type hw
  card 0
}

ctl.!default {
    type hw
    card 0
}
_EOF_

	touch /root/.no_hmdi_audio
	systemctl disable rearmit-hdmi-audio.service

} # set_hdmi_audio

case $1 in
	*start*)
		# Set HDMI to default audio output
		set_hdmi_audio &
		;;
esac
